'use client'

import { useState } from 'react'
import { X, Download, FileText, Calendar, TrendingUp, Package, Users, IndianRupee } from 'lucide-react'

interface ExportReportModalProps {
  isOpen: boolean
  onClose: () => void
  selectedPeriod: string
}

export default function ExportReportModal({ isOpen, onClose, selectedPeriod }: ExportReportModalProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  if (!isOpen) return null

  const getCurrentDate = () => {
    return new Date().toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  const generateReport = () => {
    setIsGenerating(true)
    
    // Simulate report generation
    setTimeout(() => {
      const reportData = {
        period: selectedPeriod,
        date: getCurrentDate(),
        kpis: {
          sales: '₹45,280',
          products: '248',
          customers: '1,247',
          revenue: '₹8.2L'
        },
        insights: [
          'Maggi noodles sales up 45% this week',
          '12 products below minimum level',
          'Diwali in 15 days - prepare inventory'
        ]
      }

      // Create CSV content
      const csvContent = `Retail Boss - Dashboard Report
Period: ${selectedPeriod}
Generated: ${reportData.date}

KEY PERFORMANCE INDICATORS
Today's Sales,${reportData.kpis.sales}
Total Products,${reportData.kpis.products}
Active Customers,${reportData.kpis.customers}
Monthly Revenue,${reportData.kpis.revenue}

AI-POWERED INSIGHTS
${reportData.insights.map(insight => `"${insight}"`).join('\n')}

---
Generated by Retail Boss AI-Powered POS System
`

      // Create blob and download
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      const url = URL.createObjectURL(blob)
      link.setAttribute('href', url)
      link.setAttribute('download', `Retail_Boss_Report_${selectedPeriod.replace(/\s+/g, '_')}_${new Date().getTime()}.csv`)
      link.style.visibility = 'hidden'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      
      setIsGenerating(false)
      onClose()
    }, 1500)
  }

  return (
    <div
      className="fixed inset-0 bg-black/50 z-[1000] flex items-center justify-center p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl p-6 sm:p-8 max-w-2xl w-full max-h-[90vh] overflow-y-auto animate-modal-slide-in shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-6 pb-4 border-b-2 border-gray-200">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-md bg-primary text-secondary flex items-center justify-center">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl sm:text-2xl font-bold text-primary">Export Report</h2>
              <p className="text-sm text-gray-600">Preview and download your dashboard report</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-md bg-gray-100 flex items-center justify-center hover:bg-gray-200 transition-all hover:scale-105"
          >
            <X className="w-5 h-5 text-gray-600" />
          </button>
        </div>

        {/* Report Preview */}
        <div className="mb-6">
          <div className="bg-gray-50 border-2 border-gray-200 rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4 pb-3 border-b border-gray-300">
              <Calendar className="w-5 h-5 text-primary" />
              <h3 className="text-lg font-bold text-primary">Report Preview</h3>
            </div>

            {/* Report Period */}
            <div className="mb-6">
              <div className="flex items-center justify-between p-4 bg-white rounded-lg border border-gray-200 mb-3">
                <span className="text-sm font-semibold text-gray-700">Report Period:</span>
                <span className="text-base font-bold text-primary">{selectedPeriod}</span>
              </div>
              <div className="flex items-center justify-between p-4 bg-white rounded-lg border border-gray-200">
                <span className="text-sm font-semibold text-gray-700">Generated Date:</span>
                <span className="text-base font-bold text-primary">{getCurrentDate()}</span>
              </div>
            </div>

            {/* KPI Summary */}
            <div className="mb-6">
              <h4 className="text-sm font-bold text-gray-700 uppercase tracking-wide mb-3">Key Performance Indicators</h4>
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-white p-4 rounded-lg border border-gray-200">
                  <div className="flex items-center gap-2 mb-2">
                    <IndianRupee className="w-4 h-4 text-primary" />
                    <span className="text-xs text-gray-600 font-medium">Today's Sales</span>
                  </div>
                  <p className="text-lg font-bold text-primary">₹45,280</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-gray-200">
                  <div className="flex items-center gap-2 mb-2">
                    <Package className="w-4 h-4 text-primary" />
                    <span className="text-xs text-gray-600 font-medium">Total Products</span>
                  </div>
                  <p className="text-lg font-bold text-primary">248</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-gray-200">
                  <div className="flex items-center gap-2 mb-2">
                    <Users className="w-4 h-4 text-primary" />
                    <span className="text-xs text-gray-600 font-medium">Active Customers</span>
                  </div>
                  <p className="text-lg font-bold text-primary">1,247</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-gray-200">
                  <div className="flex items-center gap-2 mb-2">
                    <TrendingUp className="w-4 h-4 text-primary" />
                    <span className="text-xs text-gray-600 font-medium">Monthly Revenue</span>
                  </div>
                  <p className="text-lg font-bold text-primary">₹8.2L</p>
                </div>
              </div>
            </div>

            {/* AI Insights */}
            <div>
              <h4 className="text-sm font-bold text-gray-700 uppercase tracking-wide mb-3">AI-Powered Insights</h4>
              <div className="space-y-2">
                <div className="bg-white p-3 rounded-lg border-l-4 border-primary">
                  <p className="text-sm text-gray-800">• Maggi noodles sales up 45% this week</p>
                </div>
                <div className="bg-white p-3 rounded-lg border-l-4 border-warning">
                  <p className="text-sm text-gray-800">• 12 products below minimum level</p>
                </div>
                <div className="bg-white p-3 rounded-lg border-l-4 border-primary">
                  <p className="text-sm text-gray-800">• Diwali in 15 days - prepare inventory</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* File Format Info */}
        <div className="mb-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-semibold text-primary mb-1">Report Format</p>
              <p className="text-xs text-gray-600">The report will be downloaded as a CSV file containing all dashboard metrics and insights for easy analysis.</p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={onClose}
            className="flex-1 bg-white text-primary border-2 border-gray-300 px-6 py-3 rounded-md text-sm sm:text-base font-semibold cursor-pointer transition-all hover:bg-gray-100 hover:border-primary hover:scale-[1.02]"
          >
            Cancel
          </button>
          <button
            onClick={generateReport}
            disabled={isGenerating}
            className="flex-1 bg-primary text-secondary border-none px-6 py-3 rounded-md text-sm sm:text-base font-semibold cursor-pointer flex items-center justify-center gap-2 transition-all hover:bg-primary-light hover:scale-[1.02] hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <div className="w-5 h-5 border-2 border-secondary border-t-transparent rounded-full animate-spin"></div>
                Generating...
              </>
            ) : (
              <>
                <Download className="w-5 h-5" />
                Download Report
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  )
}

