-- Sales Bill (IMMUTABLE)
-- Represents a completed sales transaction
-- RULE: Bills cannot be deleted or modified after creation

CREATE TABLE IF NOT EXISTS sales_bill (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bill_number TEXT UNIQUE NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    tax_amount NUMERIC(10,2) NOT NULL CHECK (tax_amount >= 0),
    total NUMERIC(10,2) NOT NULL CHECK (total >= 0),
    payment_mode TEXT NOT NULL CHECK (payment_mode IN ('cash', 'upi', 'card')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sales_bill_bill_number ON sales_bill(bill_number);
CREATE INDEX IF NOT EXISTS idx_sales_bill_created_at ON sales_bill(created_at);

-- Comments
COMMENT ON TABLE sales_bill IS 'IMMUTABLE sales bills. Once created, cannot be modified or deleted.';
COMMENT ON COLUMN sales_bill.bill_number IS 'Unique bill number generated by system';
COMMENT ON COLUMN sales_bill.subtotal IS 'Subtotal before tax';
COMMENT ON COLUMN sales_bill.tax_amount IS 'Total tax amount';
COMMENT ON COLUMN sales_bill.total IS 'Final total amount (subtotal + tax)';

-- Prevent updates and deletes
CREATE OR REPLACE FUNCTION prevent_bill_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'sales_bill is immutable. Updates and deletes are not allowed.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER prevent_sales_bill_update
    BEFORE UPDATE ON sales_bill
    FOR EACH ROW
    EXECUTE FUNCTION prevent_bill_mutation();

CREATE TRIGGER prevent_sales_bill_delete
    BEFORE DELETE ON sales_bill
    FOR EACH ROW
    EXECUTE FUNCTION prevent_bill_mutation();